apiVersion: v1
kind: List
items:

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: tempo-query
    labels:
      name: tempo
  data:
    tempo-query.yaml: |
      backend: "tempo:3200"
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: tempo
    labels:
      name: tempo
  data:
    tempo.yaml: |
      server:
        http_listen_port: 3200
      search_enabled: true
      distributor:
        receivers:                           # this configuration will listen on all ports and protocols that tempo is capable of.
          jaeger:                            # the receives all come from the OpenTelemetry collector.  more configuration information can
            protocols:                       # be found there: https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver
              thrift_http:                   #
              grpc:                          # for a production deployment you should only enable the receivers you need!
              thrift_binary:
              thrift_compact:
          zipkin:
          otlp:
            protocols:
              http:
              grpc:
          opencensus:
      ingester:
        complete_block_timeout: 10s
        trace_idle_period: 10s               # the length of time after a trace has not received spans to consider it complete and flush it
        max_block_duration: 15m               #   this much time passes
      query_frontend:
        search:
          max_result_limit: 0
          query_backend_after: 10m
          query_ingesters_until: 15m
          max_duration: 0
      
      compactor:
        compaction:
          compaction_window: 1h              # blocks in this time window will be compacted together
          max_block_bytes: 100_000_000        # maximum size of compacted blocks
          flush_size_bytes: 5242880
      
      overrides:
        max_search_bytes_per_trace: 50000
      
      storage:
        trace:
          backend: gcs                       # backend configuration to use
          block:
            bloom_filter_false_positive: .05 # bloom filter false positive rate.  lower values create larger filters but fewer false positives
            index_downsample_bytes: 1000     # number of bytes per index record
            encoding: zstd                   # block encoding/compression.  options: none, gzip, lz4-64k, lz4-256k, lz4-1M, lz4, snappy, zstd, s2
          wal:
            path: /tmp/tempo/wal             # where to store the the wal locally
            encoding: zstd                 # wal encoding/compression.  options: none, gzip, lz4-64k, lz4-256k, lz4-1M, lz4, snappy, zstd, s2
          # local:
          #   path: /tmp/tempo/blocks
          gcs:
            bucket_name: tempo-lg
            endpoint: https://storage.googleapis.com/storage/v1/
            insecure: true
          pool:
            max_workers: 100                 # worker pool determines the number of parallel requests to the object store backend
            queue_depth: 10000
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: tempo
    labels:
      name: tempo
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: tempo
    serviceName: tempo
    template:
      metadata:
        labels:
          name: tempo
      spec:
        containers:
        - name: tempo
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/key.json
          args:
          - -search.enabled=true
          - -config.file=/conf/tempo.yaml
          - -mem-ballast-size-mbs=1024
          image: grafana/tempo:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 6831
            name: jaeger-thrift-c
            protocol: UDP
          - containerPort: 6832
            name: jaeger-thrift-b
            protocol: UDP
          - containerPort: 14268
            name: jaeger-thrift-h
          - containerPort: 14250
            name: jaeger-grpc
          - containerPort: 9411
            name: zipkin
          - containerPort: 55680
            name: otlp-legacy
          - containerPort: 4317
            name: otlp-grpc
          - containerPort: 55681
            name: otlp-http
          - containerPort: 55678
            name: opencensus
          volumeMounts:
          - mountPath: /conf
            name: tempo-conf
          - mountPath: /tmp/tempo
            name: tempo-data
          - name: google-cloud-key
            mountPath: /var/key.json
          resources:
            requests:
              memory: 9Gi
        - name: tempo-query
          args:
          - --grpc-storage-plugin.configuration-file=/conf/tempo-query.yaml
          image: grafana/tempo-query:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 16686
            name: jaeger-ui
          volumeMounts:
          - mountPath: /conf
            name: tempo-query-conf
        volumes:
        - name: tempo-data
          emptyDir: {}
        - configMap:
            name: tempo-query
          name: tempo-query-conf
        - configMap:
            name: tempo
          name: tempo-conf
        - name: google-cloud-key
          secret:
            secretName: pubsub-key
    updateStrategy:
      type: RollingUpdate
- apiVersion: v1
  kind: Service
  metadata:
    name: tempo
    labels:
      app: tempo

  spec:
    type: LoadBalancer
    ports:
    - name: jaeger-ui
      port: 16686
      targetPort: 16686
    - name: tempo-jaeger-thrift-http
      port: 14268
      protocol: TCP
      targetPort: 14268
    - name: grpc-tempo-jaeger
      port: 14250
      protocol: TCP
      targetPort: 14250
    - name: tempo-zipkin
      port: 9411
      protocol: TCP
      targetPort: 9411
    - name: tempo-otlp-legacy
      port: 55680
      protocol: TCP
      targetPort: 55680
    - name: tempo-otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: grpc-tempo-otlp
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: tempo-opencensus
      port: 55678
      protocol: TCP
      targetPort: 55678
    - name: tempo-server
      port: 3200
      targetPort: 3200
    selector:
      name: tempo
