apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracegen
spec:
  selector:
    matchLabels:
      app: tracegen
  template:
    metadata:
      labels:
        app: tracegen
    spec:
      containers:
      - name: tracegen
        image: docker.io/jessberg/tracegenlargequeue:latest
        # it won't allow me to do this without a duration, so you just make the duration about a day;  no way an experiment takes longer than that
        args: ["-otlp-insecure", "-rate", "500", "-otlp-endpoint", "otelcollector:4317", "-duration", "50s", "--workers", "1"]
        resources:
            requests:
                memory: 5Gi
            limits:
                memory: 7Gi

---
apiVersion: v1
kind: Service
metadata:
  name: tracegen
spec:
  type: ClusterIP 
  selector:
    app: tracegen
  ports:
  - name: "4317"
    port: 4317
    targetPort: 4317
