apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracegen
spec:
  selector:
    matchLabels:
      app: tracegen
  template:
    metadata:
      labels:
        app: tracegen
    spec:
      containers:
      - name: tracegen
        image: docker.io/jessberg/tracegenerator
        args: ["-otlp-insecure", "-rate", "500", "-otlp-endpoint", "otelcollector:4317", "-duration", "2000s"]

---
apiVersion: v1
kind: Service
metadata:
  name: tracegen
spec:
  type: ClusterIP 
  selector:
    app: tracegen
  ports:
  - name: "4317"
    port: 4317
    targetPort: 4317
