receivers:
 jaeger:
   protocols:
     thrift_compact:

processors:
 batch:

exporters:
 logging:

service:
 pipelines:
   traces:
     receivers: [jaeger]
     processors: [batch]
     exporters: [logging]
