apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: hotrod
    app.kubernetes.io/instance: hotrod
  name: hotrod
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: hotrod
      app.kubernetes.io/instance: hotrod
      app.kubernetes.io/name: hotrod
  template:
    metadata:
      labels:
        app.kubernetes.io/component: hotrod
        app.kubernetes.io/instance: hotrod
        app.kubernetes.io/name: hotrod
    spec:
      containers:
      - env:
        - name: JAEGER_AGENT_HOST
          value: otelcollector
        - name: JAEGER_AGENT_PORT
          value: "6831"
        image: jaegertracing/example-hotrod:latest
        name: hotrod
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: hotrod
    app.kubernetes.io/instance: hotrod
  name: hotrod
spec:
  ports:
  - name: hotrod
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/component: hotrod
    app.kubernetes.io/instance: hotrod
  type: LoadBalancer
