apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcollector
spec:
  selector:
    matchLabels:
      app: otelcollector
  template:
    metadata:
      labels:
        app: otelcollector
    spec:
      containers:
      - name: otelcollector
        args:
        - --config=/conf/collector-gateway-config-template.yaml
        image: otel/opentelemetry-collector:0.23.0
        imagePullPolicy: Always
        volumeMounts:
        - name: collector-gateway-config-template
          mountPath: /conf
      volumes:
      # Simple ConfigMap volume with template file
      - name: collector-gateway-config-template
        configMap:
          name: collector-gateway-config-template
---
apiVersion: v1
kind: Service
metadata:
  name: otelcollector
spec:
  type: ClusterIP
  selector:
    app: otelcollector
  ports:
  - name: "6831"
    port: 6831
    targetPort: 6831
  - name: "6832"
    port: 6832
    targetPort: 6832
---
apiVersion: v1                                                                  
kind: ConfigMap                                                                 
metadata:                                                                       
  name: collector-gateway-config-template                                       
# Open Telemetry Collector config                                               
# https://opentelemetry.io/docs/collector/configuration/                        
data:                                                                           
  collector-gateway-config-template.yaml: |
    receivers:
      jaeger:
        protocols:
          thrift_compact:
    
    exporters:
      logging:
    
    processors:
      batch:

    service:                                                                    
      pipelines:                                                                
        traces:                                                                 
          receivers: [jaeger] # Receive otlp-formatted data from other collector instances
          processors: [batch]
          exporters: [logging]