name: docker-build-opentelemetry-collector
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build-opentelemetry:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [macos-latest, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - uses: docker-practice/actions-setup-docker@master
      if: ${{ matrix.os  == 'macos-latest' }}
    - name: Install dependencies
      run: |
        ./tools/setup.sh
    - name: Build OpenTelemetry Collector in Docker
      run: |
        sudo -E docker build .
