name: build-opentelemetry-collector
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  go-build-gcs-exporter:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [macos-latest, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18.0'
    - name: Install dependencies
      run: |
        ./tools/setup.sh
    - name: Test with go build
      run: |
        cd gcs_exporter
        go build
  go-build-load-balancer:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [macos-latest, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18.0'
    - name: Install dependencies
      run: |
        ./tools/setup.sh
    - name: Test with go build
      run: |
        cd loadbalancerhttp
        go version
        go build
